### ISSUE TITLE
Exception: FAILED BINDER TRANSACTION

### ISSUE THREAD

**Issue by Lime-blur** [massivemadness/EditorKit#2]
Hello! When importing the content of a file into the code editor, when the file size exceeds 500 KB, the application either crashes and throws the following error:
`E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 1244864)
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1244864 bytes
        at android.view.autofill.AutofillManager.startSessionLocked(AutofillManager.java:844)
        at android.view.autofill.AutofillManager.notifyViewEntered(AutofillManager.java:467)
        at android.view.autofill.AutofillManager.notifyViewEntered(AutofillManager.java:446)
        at android.view.View.notifyEnterOrExitForAutoFillIfNeeded(View.java:6980)
        at android.view.View.performClick(View.java:6302)
        at android.view.View$PerformClick.run(View.java:24931)
        at android.os.Handler.handleCallback(Handler.java:808)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7529)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
     Caused by: android.os.TransactionTooLargeException: data parcel size 1244864 bytes
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:753)
        at android.view.autofill.IAutoFillManager$Stub$Proxy.startSession(IAutoFillManager.java:385)
        at android.view.autofill.AutofillManager.startSessionLocked(AutofillManager.java:836)`

**Comment by massivemadness** [comment]
Hi @Lime-blur, you can set [`freezesText`](https://github.com/massivemadness/Squircle-CE/blob/master/feature-editor-impl/src/main/kotlin/com/blacksquircle/ui/feature/editor/ui/fragment/EditorFragment.kt#L144) property to `false`, which means that the text won't be saved into Parcelable. But then you have to keep the text somewhere else outside the view (ex. ViewModel, StateFlow) and make sure it is restored on configuration changes.
